<?php

defined('ABSPATH') || exit;

require_once __DIR__ . '/Helpers.php';
require_once __DIR__ . '/Cache.php';
require_once __DIR__ . '/PriceEngine.php';
require_once __DIR__ . '/GraphQL.php';
require_once __DIR__ . '/Scheduler.php';
require_once __DIR__ . '/Revalidator.php';
require_once __DIR__ . '/Admin.php';
require_once __DIR__ . '/SecureVault.php';
require_once __DIR__ . '/SecureFields.php';
require_once __DIR__ . '/OrderSecurityHooks.php';
require_once __DIR__ . '/OrderFulfillment.php';
require_once __DIR__ . '/Notifications.php';
require_once __DIR__ . '/Sessions.php';
require_once __DIR__ . '/TicketReplies.php';
require_once __DIR__ . '/TicketAdmin.php';
require_once __DIR__ . '/WishlistAlerts.php';
require_once __DIR__ . '/CustomerTickets.php';
require_once __DIR__ . '/CustomerReviews.php';
require_once __DIR__ . '/ReviewModeration.php';
require_once __DIR__ . '/AvatarGuard.php';
require_once __DIR__ . '/CdKeyStock.php';
require_once __DIR__ . '/CdKeyAdmin.php';
require_once __DIR__ . '/BlogFollow.php';
require_once __DIR__ . '/PostRatings.php';
require_once __DIR__ . '/BlogComments.php';

BTL_Price_Engine::boot();
BTL_GraphQL::boot();
BTL_Scheduler::boot();
BTL_Revalidator::boot();
BTL_Admin::boot();
BTL_Secure_Fields::boot();
BTL_Order_Security_Hooks::boot();
BTL_Order_Fulfillment::boot();
BTL_Notifications::boot();
BTL_Sessions::boot();
BTL_Ticket_Replies::boot();
BTL_Ticket_Admin::boot();
BTL_Wishlist_Alerts::boot();
BTL_Customer_Tickets::boot();
BTL_Customer_Reviews::boot();
BTL_Review_Moderation::boot();
BTL_Avatar_Guard::boot();
BTL_CdKey_Stock::boot();
BTL_CdKey_Admin::boot();
BTL_Blog_Follow::boot();
BTL_Post_Ratings::boot();
BTL_Blog_Comments::boot();